matrix:
  include:
    - os: linux
      sudo: required
      dist: focal
      compiler: gcc
    - os: linux
      sudo: required
      dist: bionic
      compiler: gcc
    - os: linux
      sudo: required
      dist: xenial
      compiler: gcc
    - os: osx
      osx_image: xcode10.3

language: cpp

before_install:
# GLPK specific part
#-----------------------
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install glpk; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; sudo apt-get install -y libglpk-dev; fi
# End of GLPK specific part
#-----------------------
  - MY_LOCATION=`pwd`
  - mkdir ../repositories
  - cd ..
  - mv $MY_LOCATION repositories
  - QUICKY_REPOSITORY=`pwd`/repositories
  - export QUICKY_REPOSITORY
  - MY_LOCATION=`pwd`
  - cd $MY_LOCATION/repositories
  - git clone https://github.com/quicky2000/quicky_tools.git
  - cd quicky_tools/setup
  - . setup.sh
  - cd $MY_LOCATION
  - chmod a+x repositories/quicky_tools/bin/*
  - mkdir build
  - cd build

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then generate_makefile EXT_glpk; make test; ./bin/EXT_glpk.exe; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd $MY_LOCATION ; mkdir cmake_build ; cd cmake_build ; fi
  - cmake $QUICKY_REPOSITORY/EXT_glpk
  - make
  - ./test_EXT_glpk
#EOF
